# https://docs.netlify.com/configure-builds/file-based-configuration/
[build]
	base = "/"
	publish = ".tmp/"
	command = "npm run build"
	# functions = "functions/"
	skip_processing = true

[build.environment]
	NPM_FLAGS="--prefix=/"

# [context.production]
# [context.deploy-preview]
# [context.branch-deploy]
# [context.staging] # 'staging' is a branch name

[[redirects]]
	from = "https://o137-typing.netlify.app/*"
	to = "https://typing.o137.dev/:splat"
	status = 301
	force = true

[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200
	force = false
	# query = {path = ":path"}
	# conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
	# headers = {X-From = "Netlify"}
	# signed = "API_SIGNATURE_TOKEN"

# TODO: Add 404 error page

# [[headers]]